//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DshInterview.Domain
{
    public partial class Customer
    {
        #region Primitive Properties
    
        public virtual int CustomerID
        {
            get;
            set;
        }
    
        public virtual string CustomerName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual System.DateTime CustomerSince
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Sale> Sales
        {
            get
            {
                if (_sales == null)
                {
                    var newCollection = new FixupCollection<Sale>();
                    newCollection.CollectionChanged += FixupSales;
                    _sales = newCollection;
                }
                return _sales;
            }
            set
            {
                if (!ReferenceEquals(_sales, value))
                {
                    var previousValue = _sales as FixupCollection<Sale>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSales;
                    }
                    _sales = value;
                    var newValue = value as FixupCollection<Sale>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSales;
                    }
                }
            }
        }
        private ICollection<Sale> _sales;

        #endregion
        #region Association Fixup
    
        private void FixupSales(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Sale item in e.NewItems)
                {
                    item.Customer = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Sale item in e.OldItems)
                {
                    if (ReferenceEquals(item.Customer, this))
                    {
                        item.Customer = null;
                    }
                }
            }
        }

        #endregion
    }
}
