//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DshInterview.Domain
{
    public partial class Product
    {
        #region Primitive Properties
    
        public virtual int ProductID
        {
            get;
            set;
        }
    
        public virtual string ProductName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual decimal PricePerUnit
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<SoldProduct> SoldProducts
        {
            get
            {
                if (_soldProducts == null)
                {
                    var newCollection = new FixupCollection<SoldProduct>();
                    newCollection.CollectionChanged += FixupSoldProducts;
                    _soldProducts = newCollection;
                }
                return _soldProducts;
            }
            set
            {
                if (!ReferenceEquals(_soldProducts, value))
                {
                    var previousValue = _soldProducts as FixupCollection<SoldProduct>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSoldProducts;
                    }
                    _soldProducts = value;
                    var newValue = value as FixupCollection<SoldProduct>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSoldProducts;
                    }
                }
            }
        }
        private ICollection<SoldProduct> _soldProducts;

        #endregion
        #region Association Fixup
    
        private void FixupSoldProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SoldProduct item in e.NewItems)
                {
                    item.Product = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SoldProduct item in e.OldItems)
                {
                    if (ReferenceEquals(item.Product, this))
                    {
                        item.Product = null;
                    }
                }
            }
        }

        #endregion
    }
}
