//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DshInterview.Domain
{
    public partial class Sale
    {
        #region Primitive Properties
    
        public virtual int SaleID
        {
            get;
            set;
        }
    
        public virtual System.DateTime SaleDate
        {
            get;
            set;
        }
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual int CustomerID
        {
            get { return _customerID; }
            set
            {
                if (_customerID != value)
                {
                    if (Customer != null && Customer.CustomerID != value)
                    {
                        Customer = null;
                    }
                    _customerID = value;
                }
            }
        }
        private int _customerID;

        #endregion
        #region Navigation Properties
    
        public virtual Customer Customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    FixupCustomer(previousValue);
                }
            }
        }
        private Customer _customer;
    
        public virtual ICollection<SoldProduct> SoldProducts
        {
            get
            {
                if (_soldProducts == null)
                {
                    var newCollection = new FixupCollection<SoldProduct>();
                    newCollection.CollectionChanged += FixupSoldProducts;
                    _soldProducts = newCollection;
                }
                return _soldProducts;
            }
            set
            {
                if (!ReferenceEquals(_soldProducts, value))
                {
                    var previousValue = _soldProducts as FixupCollection<SoldProduct>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSoldProducts;
                    }
                    _soldProducts = value;
                    var newValue = value as FixupCollection<SoldProduct>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSoldProducts;
                    }
                }
            }
        }
        private ICollection<SoldProduct> _soldProducts;

        #endregion
        #region Association Fixup
    
        private void FixupCustomer(Customer previousValue)
        {
            if (previousValue != null && previousValue.Sales.Contains(this))
            {
                previousValue.Sales.Remove(this);
            }
    
            if (Customer != null)
            {
                if (!Customer.Sales.Contains(this))
                {
                    Customer.Sales.Add(this);
                }
                if (CustomerID != Customer.CustomerID)
                {
                    CustomerID = Customer.CustomerID;
                }
            }
        }
    
        private void FixupSoldProducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SoldProduct item in e.NewItems)
                {
                    item.Sale = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SoldProduct item in e.OldItems)
                {
                    if (ReferenceEquals(item.Sale, this))
                    {
                        item.Sale = null;
                    }
                }
            }
        }

        #endregion
    }
}
